info:
    app:
        description: Master Spring Boot
        name: Spring Boot Master Class Course
        version: 1.0.0
    company:
        founder: Nelson Djalo
        name: Amigoscode
    message: Hello world!
logging:
    file:
        name: logs/my.log
    level:
        org:
            hibernate: error
            springframework:
                web: error
        root: info
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
    health:
        env:
            enabled: true
    info:
        env:
            enabled: true
server:
    error:
        include-biding-errors: always
        include-message: always
        include-stacktrace: on_param
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    main:
        banner-mode: 'off'
